# Generated by Django 5.0.6 on 2024-05-18 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInfoTales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tales', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=20)),
                ('count_lessons', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LearnedWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AllLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_file', models.FileField(blank=True, null=True, upload_to='lessons/')),
                ('all_info_tales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.allinfotales')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_completed_lessons', models.IntegerField()),
                ('completed_tales', models.IntegerField()),
                ('learned_words', models.ManyToManyField(to='main_pages.learnedwords')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('language_level', models.IntegerField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles_image/')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.characteristic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TalesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_progress', models.IntegerField()),
                ('all_info_tales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.allinfotales')),
            ],
        ),
        migrations.AddField(
            model_name='characteristic',
            name='last_completed_tales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.talesinfo'),
        ),
    ]
