# Generated by Django 5.0.6 on 2024-05-18 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='all_completed_lessons',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='completed_tales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='last_completed_tales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_pages.talesinfo'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='learned_words',
            field=models.ManyToManyField(blank=True, null=True, to='main_pages.learnedwords'),
        ),
    ]
