# Generated by Django 5.0.6 on 2024-05-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0002_alter_characteristic_all_completed_lessons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language_level',
            field=models.IntegerField(default=0),
        ),
    ]
