# Generated by Django 5.0.6 on 2024-05-18 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0003_alter_profile_language_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tales_info_progress_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_pages.talesinfo'),
        ),
    ]
