# Generated by Django 5.0.6 on 2024-05-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0004_profile_tales_info_progress_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tales_info_progress_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='tales_info_progress_id',
            field=models.ManyToManyField(blank=True, null=True, to='main_pages.talesinfo'),
        ),
    ]
